#!/bin/bash

ApiUrl="${EX_ApiUrl:-http://ex-api.localtest.me:5000}"
Html5Mode="${EX_Html5Mode:-false}"
EnableSsl="${EX_EnableSsl:-false}"
EnableAccountCreation="${EX_EnableAccountCreation:-true}"

CustomScopeDelimiter="${EX_CustomAuth__Scope__Delimiter:- }"
CustomScope="${EX_CustomAuth__Scope:-}"
CustomScopePrefix="${EX_CustomAuth__Scope__Prefix:-}"

OAuth="${EX_ConnectionStrings__OAuth:-}"
IFS=';' read -a oauthParts <<< "$OAuth"
for part in ${oauthParts[@]}
do
  key="$( cut -d '=' -f 1 <<< $part )"; echo "key: $key"
  value="$( cut -d '=' -f 2- <<< $part )"; echo "value: $value"

  if [ "$key" == "FacebookId" ]; then
    FacebookAppId=$value
  fi
  if [ "$key" == "GitHubId" ]; then
    GitHubAppId=$value
  fi
  if [ "$key" == "GoogleId" ]; then
    GoogleAppId=$value
  fi
  if [ "$key" == "IntercomId" ]; then
    IntercomAppId=$value
  fi
  if [ "$key" == "MicrosoftId" ]; then
    MicrosoftAppId=$value
  fi
  if [ "$key" == "SlackId" ]; then
    SlackAppId=$value
  fi
  if [ "$key" == "CustomId" ]; then
    CustomId=$value
  fi
  if [ "$key" == "CustomAuthEndpoint" ]; then
    CustomAuthEndpoint=$value
  fi
  if [ "$key" == "CustomRequiredParams" ]; then
    CustomRequiredParams=$value
  fi
  if [ "$key" == "CustomOptionalParams" ]; then
    CustomOptionalParams=$value
  fi
done

config="(function () {
  'use strict';

  angular.module('app.config', [])
    .constant('BASE_URL', '$ApiUrl')
    .constant('EXCEPTIONLESS_API_KEY', '$EX_ExceptionlessApiKey')
    .constant('EXCEPTIONLESS_SERVER_URL', '$EX_ExceptionlessServerUrl')
    .constant('FACEBOOK_APPID', '$FacebookAppId')
    .constant('GITHUB_APPID', '$GitHubAppId')
    .constant('GOOGLE_APPID', '$GoogleAppId')
    .constant('INTERCOM_APPID', '$IntercomAppId')
    .constant('LIVE_APPID', '$MicrosoftAppId')
    .constant('SLACK_APPID', '$SlackAppId')
	.constant('CUSTOM_APPID', '$CustomId')
    .constant('CUSTOM_NAME', '$CustomName')
    .constant('CUSTOM_AUTH_ENDPOINT', '$CustomAuthEndpoint')
    .constant('CUSTOM_SCOPE', '$CustomScope')
    .constant('CUSTOM_SCOPE_PREFIX', '$CustomScopePrefix')
    .constant('CUSTOM_SCOPE_DELIMITER', '$CustomScopeDelimiter')
    .constant('CUSTOM_REQUIRED_PARAMS', '$CustomRequiredParams')
    .constant('CUSTOM_OPTIONAL_PARAMS', '$CustomOptionalParams')
    .constant('STRIPE_PUBLISHABLE_KEY', '$EX_StripePublishableApiKey')
    .constant('SYSTEM_NOTIFICATION_MESSAGE', '$EX_NotificationMessage')
    .constant('USE_HTML5_MODE', $Html5Mode)
    .constant('USE_SSL', $EnableSsl)
    .constant('ENABLE_ACCOUNT_CREATION', $EnableAccountCreation);
}());"

checksum=`echo -n $config | md5sum | cut -c 1-32`
echo $config > "/app/app.config.$checksum.js"
sed -i -E "s/app\.config\..+\.js/app.config.$checksum.js/" /app/index.html

echo "Running NGINX"
nginx
